//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Unito.EUCases.CrawlersUploader
{ 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xsdDocumentgroup")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="xsdDocumentgroup", IsNullable=false)]
public partial class documentgroup {
    
    private documentgroupDocument[] documentField;
    
    private System.DateTime dateField;
    
    private string crawlerField;
    
    private string langField;
    
    private documentgroupFormat formatField;
    
    private string filenameField;
    
    private string identifierField;
    
    private documentgroupOperation operationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("document")]
    public documentgroupDocument[] document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string crawler {
        get {
            return this.crawlerField;
        }
        set {
            this.crawlerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public documentgroupFormat format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public documentgroupOperation operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xsdDocumentgroup")]
public partial class documentgroupDocument {
    
    private documentgroupDocumentFormat formatField;
    
    private string fileField;
    
    private string identifierField;
    
    private documentgroupDocumentOperation operationField;
    
    private string urlField;
    
    private string md5Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public documentgroupDocumentFormat format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public documentgroupDocumentOperation operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string md5 {
        get {
            return this.md5Field;
        }
        set {
            this.md5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xsdDocumentgroup")]
public enum documentgroupDocumentFormat {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("application/zip")]
    applicationzip,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("application/gzip")]
    applicationgzip,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("application/pdf")]
    applicationpdf,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/gif")]
    imagegif,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/jpeg")]
    imagejpeg,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/png")]
    imagepng,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/tiff")]
    imagetiff,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/bmp")]
    imagebmp,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/css")]
    textcss,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/html")]
    texthtml,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/htm")]
    texthtm,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/javascript")]
    textjavascript,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/xml")]
    textxml,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xsdDocumentgroup")]
public enum documentgroupDocumentOperation {
    
    /// <remarks/>
    Add,
    
    /// <remarks/>
    Upd,
    
    /// <remarks/>
    Del,
    
    /// <remarks/>
    None,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xsdDocumentgroup")]
public enum documentgroupFormat {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("application/zip")]
    applicationzip,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("application/gzip")]
    applicationgzip,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("application/pdf")]
    applicationpdf,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/gif")]
    imagegif,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/jpeg")]
    imagejpeg,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/png")]
    imagepng,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/tiff")]
    imagetiff,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("image/bmp")]
    imagebmp,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/css")]
    textcss,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/html")]
    texthtml,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/htm")]
    texthtm,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/javascript")]
    textjavascript,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/xml")]
    textxml,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="xsdDocumentgroup")]
public enum documentgroupOperation {
    
    /// <remarks/>
    Add,
    
    /// <remarks/>
    Upd,
    
    /// <remarks/>
    Del,
    
    /// <remarks/>
    None,
}
}